import os, json
base_dir = r"C:\Users\pushk\Desktop\Fun\Work\Portfolio"
os.makedirs(os.path.join(base_dir, "src", "components"), exist_ok=True)
pkg = {"name":"portfolio", "private":True, "version":"0.0.0", "type":"module", "scripts":{"dev":"vite","build":"vite build","lint":"eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0","preview":"vite preview"}, "dependencies":{"react":"^18.2.0","react-dom":"^18.2.0","lucide-react":"^0.292.0"}, "devDependencies":{"@types/react":"^18.2.15","@types/react-dom":"^18.2.7","@vitejs/plugin-react":"^4.0.3","autoprefixer":"^10.4.16","eslint":"^8.45.0","eslint-plugin-react":"^7.32.2","eslint-plugin-react-hooks":"^4.6.0","eslint-plugin-react-refresh":"^0.4.3","postcss":"^8.4.31","tailwindcss":"^3.3.3","vite":"^4.4.5"}}
with open(os.path.join(base_dir, "package.json"), "w") as f: json.dump(pkg, f, indent=2)
with open(os.path.join(base_dir, "vite.config.js"), "w") as f: f.write("import { defineConfig } from \"vite\"\nimport react from \"@vitejs/plugin-react\"\nexport default defineConfig({plugins: [react()]})")
with open(os.path.join(base_dir, "index.html"), "w") as f: f.write("<!doctype html>\n<html lang=\"en\" class=\"scroll-smooth\">\n<head>\n<meta charset=\"UTF-8\" />\n<link rel=\"icon\" type=\"image/svg+xml\" href=\"/vite.svg\" />\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n<title>Software Engineer Portfolio</title>\n</head>\n<body class=\"bg-slate-900 text-slate-100 font-sans antialiased\">\n<div id=\"root\"></div>\n<script type=\"module\" src=\"/src/main.jsx\"></script>\n</body>\n</html>")
with open(os.path.join(base_dir, "tailwind.config.js"), "w") as f: f.write("/** @type {import(\"tailwindcss\").Config} */\nexport default {\ncontent: [\"./index.html\", \"./src/**/*.{js,ts,jsx,tsx}\"],\ntheme: {extend: {}},\nplugins: [],\n}")
with open(os.path.join(base_dir, "postcss.config.js"), "w") as f: f.write("export default {plugins: {tailwindcss: {},autoprefixer: {},},}")
with open(os.path.join(base_dir, "src", "main.jsx"), "w") as f: f.write("import React from \"react\"\nimport ReactDOM from \"react-dom/client\"\nimport App from \"./App.jsx\"\nimport \"./index.css\"\nReactDOM.createRoot(document.getElementById(\"root\")).render(\n<React.StrictMode>\n<App />\n</React.StrictMode>\n)")
with open(os.path.join(base_dir, "src", "index.css"), "w") as f: f.write("@tailwind base;\n@tailwind components;\n@tailwind utilities;\nbody {margin: 0;}")
with open(os.path.join(base_dir, "src", "App.jsx"), "w") as f: f.write("import Navbar from \"./components/Navbar\";\nimport Hero from \"./components/Hero\";\nimport About from \"./components/About\";\nimport Experience from \"./components/Experience\";\nimport Projects from \"./components/Projects\";\nimport Contact from \"./components/Contact\";\nimport Footer from \"./components/Footer\";\nfunction App() {\nreturn (\n<div className=\"min-h-screen\">\n<Navbar />\n<main>\n<Hero />\n<About />\n<Experience />\n<Projects />\n<Contact />\n</main>\n<Footer />\n</div>\n);\n}\nexport default App;")
print("Done")
